LOG_LEVEL: debug

POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DBNAME: bucket_store
POSTGRESQL_USER: bucket_store_admin
POSTGRESQL_PASSWORD: azerty

STORAGE_TYPE: pgsql

SERVICE_PORT: 8080