LOG_LEVEL: debug

POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DBNAME: object_store
POSTGRESQL_USER: object_store_admin
POSTGRESQL_PASSWORD: azerty

STORAGE_TYPE: memory

SERVICE_PORT: 8080