// Code generated by go-swagger; DO NOT EDIT.

// Package server Bucket storage service
//
//  Stores objects organized in buckets.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package server
