// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ObjectID Stored object id
//
// swagger:model objectId
type ObjectID struct {

	// Stored object id
	ID string `json:"id,omitempty"`
}

// Validate validates this object Id
func (m *ObjectID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this object Id based on context it is used
func (m *ObjectID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ObjectID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ObjectID) UnmarshalBinary(b []byte) error {
	var res ObjectID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
