// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetObjectHandlerFunc turns a function with the right signature into a get object handler
type GetObjectHandlerFunc func(GetObjectParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetObjectHandlerFunc) Handle(params GetObjectParams) middleware.Responder {
	return fn(params)
}

// GetObjectHandler interface for that can handle valid get object params
type GetObjectHandler interface {
	Handle(GetObjectParams) middleware.Responder
}

// NewGetObject creates a new http.Handler for the get object operation
func NewGetObject(ctx *middleware.Context, handler GetObjectHandler) *GetObject {
	return &GetObject{Context: ctx, Handler: handler}
}

/* GetObject swagger:route GET /objects/{bucket}/{objectID} getObject

Download an object from the service

*/
type GetObject struct {
	Context *middleware.Context
	Handler GetObjectHandler
}

func (o *GetObject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetObjectParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
