// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aminesnow/redhat_cc/restapi/models"
)

// UploadObjectCreatedCode is the HTTP code returned for type UploadObjectCreated
const UploadObjectCreatedCode int = 201

/*UploadObjectCreated Object created

swagger:response uploadObjectCreated
*/
type UploadObjectCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ObjectID `json:"body,omitempty"`
}

// NewUploadObjectCreated creates UploadObjectCreated with default headers values
func NewUploadObjectCreated() *UploadObjectCreated {

	return &UploadObjectCreated{}
}

// WithPayload adds the payload to the upload object created response
func (o *UploadObjectCreated) WithPayload(payload *models.ObjectID) *UploadObjectCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload object created response
func (o *UploadObjectCreated) SetPayload(payload *models.ObjectID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadObjectCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UploadObjectInternalServerErrorCode is the HTTP code returned for type UploadObjectInternalServerError
const UploadObjectInternalServerErrorCode int = 500

/*UploadObjectInternalServerError Failed to store object.

swagger:response uploadObjectInternalServerError
*/
type UploadObjectInternalServerError struct {
}

// NewUploadObjectInternalServerError creates UploadObjectInternalServerError with default headers values
func NewUploadObjectInternalServerError() *UploadObjectInternalServerError {

	return &UploadObjectInternalServerError{}
}

// WriteResponse to the client
func (o *UploadObjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
